baseURL = 'https://dancarroll.org/'
defaultContentLanguage = "en"
languageCode = 'en-us'
title = 'Dan Carroll'
theme = "dancarrollorg"
copyright = "Dan Carroll"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[taxonomies]
  tag = 'tags'

[permalinks]
  [permalinks.page]
    blog = '/blog/:year/:month/:slug/'
  [permalinks.section]
    blog = '/blog/'
  [permalinks.term]
    tags = '/blog/tags/:slug/'
  [permalinks.taxonomy]
    tags = '/blog/tags/'

# Setup syntax highlighting without inline styles. For more information about
# why you'd want to avoid inline styles, see
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src#unsafe_inline_styles
[markup]
  [markup.highlight]
    lineNos = false
    lineNumbersInTable = false
    # This allows Bear Cub to use a variation of Dracula that is more accessible
    # to people with poor eyesight. For more information about color contrast
    # and accessibility, see https://web.dev/color-and-contrast-accessibility/
    noClasses = false

[services]
  [services.disqus]
    shortname = 'dancarroll'
  [services.googleAnalytics]
    id = 'G-PBDQ0CCMLN'
  [services.rss]
    limit = 5

[params]
  # The description of your website
  description = "Personal blog of Dan Carroll, a developer based in Massachusetts. Topics include C#, Python, Django, and gaming."

  # The path to your favicon
  favicon = "favicon.png"

  # This title is used as the site_name on the Hugo's internal opengraph
  # structured data template
  title = "Dan Carroll"

  # Dates are displayed following the format below. For more information about
  # formatting, see https://gohugo.io/functions/format/
  dateFormat = "2006-01-02"

  # Author metadata.
  [params.author]
    name = "Dan Carroll"
